/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tugas;

import javax.swing.JOptionPane;

/**
 *
 * @author SENJU
 */
public class pendaftaran extends javax.swing.JFrame {

    private Object Konsentrasi;

    /**
     * Creates new form pendaftaran
     */
    public pendaftaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bJK = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fNamaLengkap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fNIM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tFakultas = new javax.swing.JComboBox<>();
        tProdi = new javax.swing.JComboBox<>();
        fTTL = new javax.swing.JTextField();
        jPerempuan = new javax.swing.JRadioButton();
        jLaki = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fNohp = new javax.swing.JTextField();
        tKonsentrasi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bAlasan = new javax.swing.JTextArea();
        jSIMPAN = new javax.swing.JButton();
        jRESET = new javax.swing.JButton();
        jKELUAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 48)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\baims\\Downloads\\logooonew(1).jpg")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Nama Lengkap :");

        fNamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNamaLengkapActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("NIM :");

        fNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNIMActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Tempat, tanggal lahir");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Fakultas");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Prodi");

        tFakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "Hukum", "Teknik", "Pertanian", "Ilmu Pendidikan", "Ilmu Sosial dan Budaya", "Keislaman", "Ekonomi dan Bisnis" }));
        tFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFakultasActionPerformed(evt);
            }
        });

        tProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Prodi", "Ilmu Hukum", "Teknik Informatika", "Teknik Industri", "Teknik Elektro", "Sistem Informasi", "Teknik Mekatronika", "Teknik Mesin", "Agroteknologi", "Agribisnis", "Teknologi Industri Pertanian", "Ilmu Kelautan", "Manajemen Sumberdaya Perairan", "Pendidikan Guru Sekolah Dasar", "Pendidikan Guru Pendidikan Anak Usia Dini", "Pendidikan IPA", "Pendidikan Informatika", "Pendidikan Bahasa dan Sastra Indonesia", "Ilmu Komunikasi", "Sosiologi", "Sastra Inggris", "Psikologi", "Hukum Bisnis Syariah", "Ekonomi Syariah", "Akuntansi", "Manajemen", "Ekonomi Pembangunan", " ", " " }));
        tProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tProdiActionPerformed(evt);
            }
        });

        jPerempuan.setBackground(new java.awt.Color(153, 153, 255));
        bJK.add(jPerempuan);
        jPerempuan.setText("Perempuan");
        jPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPerempuanActionPerformed(evt);
            }
        });

        jLaki.setBackground(new java.awt.Color(153, 153, 255));
        bJK.add(jLaki);
        jLaki.setText("Laki-laki");
        jLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLakiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("No Handphone");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Konsentrasi Yang Dipilih");

        fNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNohpActionPerformed(evt);
            }
        });

        tKonsentrasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Konsentrasi", "Master Of Ceremony", "Presentasi", "English Speaking", "Debat", "Reporter", " " }));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Alasan Mengikuti Komunitas Public Speaking");

        bAlasan.setColumns(20);
        bAlasan.setRows(5);
        jScrollPane1.setViewportView(bAlasan);

        jSIMPAN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSIMPAN.setText("SIMPAN");
        jSIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSIMPANActionPerformed(evt);
            }
        });

        jRESET.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRESET.setText("RESET");
        jRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRESETActionPerformed(evt);
            }
        });

        jKELUAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jKELUAR.setText("KELUAR");
        jKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKELUARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(fNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64))
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tKonsentrasi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tProdi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPerempuan)
                                .addGap(26, 26, 26)
                                .addComponent(jLaki)
                                .addGap(53, 53, 53))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFakultas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(fNohp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(jLabel10)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jSIMPAN)
                .addGap(76, 76, 76)
                .addComponent(jRESET)
                .addGap(71, 71, 71)
                .addComponent(jKELUAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPerempuan)
                    .addComponent(jLaki))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKonsentrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSIMPAN)
                    .addComponent(jRESET)
                    .addComponent(jKELUAR))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNamaLengkapActionPerformed

    private void fNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNIMActionPerformed

    private void tFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFakultasActionPerformed

    private void jLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLakiActionPerformed

    private void fNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNohpActionPerformed

    private void jSIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSIMPANActionPerformed
        String NamaLengkap = fNamaLengkap.getText();
    String NIM = fNIM.getText();
    String TTL = fTTL.getText();
    String Nohp = fNohp.getText();
    String Alasan = bAlasan.getText();
    String Konsentrasi = tKonsentrasi.getSelectedItem().toString();
    String Fakultas = tFakultas.getSelectedItem().toString();
    String Prodi = tProdi.getSelectedItem().toString();
    String JenisKelamin = "Perempuan";

    if (jLaki.isSelected()) {
        JenisKelamin = "Laki-laki";
    } else if (jPerempuan.isSelected()) {
        JenisKelamin = "Perempuan";
    } else {
        JOptionPane.showMessageDialog(null, "Semua kolom harus diisi", "Data Harus Diisi", JOptionPane.ERROR_MESSAGE);
        return; // Keluar dari metode jika jenis kelamin tidak diisi.
    }

    if (NamaLengkap.isEmpty() || NIM.isEmpty() || TTL.isEmpty() || Nohp.isEmpty() || Alasan.isEmpty() || 
        (Prodi.equals("Pilih Prodi") || Fakultas.equals("Pilih Fakultas") || Konsentrasi.equals("Pilih Konsentrasi"))) {
        JOptionPane.showMessageDialog(null, "Semua kolom harus diisi", "Data Harus Diisi", JOptionPane.ERROR_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "Simpan", JOptionPane.DEFAULT_OPTION);
    }
    }//GEN-LAST:event_jSIMPANActionPerformed

    private void jKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKELUARActionPerformed
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jKELUARActionPerformed

    private void jRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRESETActionPerformed
        fNamaLengkap.setText("");
        fNIM.setText("");
        fTTL.setText("");
        fNohp.setText("");
        tKonsentrasi.setSelectedIndex(0);
        tFakultas.setSelectedIndex(0);
        tProdi.setSelectedIndex(0);
        bAlasan.setText("");
        jPerempuan.setSelected(false);
        jLaki.setSelected(false);
        bJK.clearSelection();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jRESETActionPerformed

    private void tProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tProdiActionPerformed

    private void jPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPerempuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bAlasan;
    private javax.swing.ButtonGroup bJK;
    private javax.swing.JTextField fNIM;
    private javax.swing.JTextField fNamaLengkap;
    private javax.swing.JTextField fNohp;
    private javax.swing.JTextField fTTL;
    private javax.swing.JButton jKELUAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jLaki;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jPerempuan;
    private javax.swing.JButton jRESET;
    private javax.swing.JButton jSIMPAN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> tFakultas;
    private javax.swing.JComboBox<String> tKonsentrasi;
    private javax.swing.JComboBox<String> tProdi;
    // End of variables declaration//GEN-END:variables
}
